
version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    env_file: .env
    ports:
      - "${DOCKER_PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


