
version: '3.0'

services:
  SQL_Database_mariadb:
    image: mariadb:latest
    container_name: SQL_Database_Mariadb
    restart: always
    env_file: .env
    ports:
    - "${MARIADB_PORT}:3306"
    volumes:
     - SQL_Database_mariadb_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"    
    networks:
    - SQL_Database_network

  SQL_Database_phpmyadmin:
    image: phpmyadmin
    container_name: SQL_Database_phpmyadmin
    restart: always
    env_file: .env
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
    - SQL_Database_network

volumes:
  SQL_Database_mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/max/Documents/Docker/Dockerservice/services/SQL_Database/data

networks:
  SQL_Database_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.170.0/24


